---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 33717.
--- DateTime: 2026/6/20 12:19
---
---
--- Redis 连接和操作封装模块
--- 提供完整的 Redis 数据结构操作接口，包括字符串、哈希、列表、集合、有序集合
--- 使用前需要安装 redis-lua 库: luarocks install redis-lua
---
--- 使用示例:
--- local RedisManager = require 'redisDemo'
--- RedisManager.connect('127.0.0.1', 6379, nil, 0)
--- RedisManager.set('key', 'value')
--- local value = RedisManager.get('key')
--- RedisManager.close()
---

-- 引入 redis-lua 库
local redis = require 'redis'

-- Redis 连接管理器
-- 封装 Redis 连接和操作的核心模块
local RedisManager = {
    client = nil,      -- Redis 客户端实例
    host = '127.0.0.1', -- Redis 服务器地址，默认本地
    port = 6379,       -- Redis 服务器端口，默认 6379
    password = nil,    -- Redis 密码，默认无密码
    db = 0            -- Redis 数据库编号，默认 0
}

--- 创建 Redis 连接
--- @param host string Redis 主机地址
--- @param port number Redis 端口
--- @param password string|nil 密码
--- @param db number 数据库编号
--- @return table|nil Redis 客户端
function RedisManager.connect(host, port, password, db)
    -- 设置连接参数，使用传入值或默认值
    RedisManager.host = host or RedisManager.host
    RedisManager.port = port or RedisManager.port
    RedisManager.password = password or RedisManager.password
    RedisManager.db = db or RedisManager.db

    -- 创建 Redis 连接
    local client = redis.connect(RedisManager.host, RedisManager.port)
    if not client then
        print('Redis 连接失败')
        return nil
    end

    -- 如果有密码，进行认证
    if RedisManager.password then
        local ok, err = client:auth(RedisManager.password)
        if not ok then
            print('Redis 认证失败:', err)
            return nil
        end
    end

    -- 选择数据库（如果不是默认的 0 号数据库）
    if RedisManager.db ~= 0 then
        client:select(RedisManager.db)
    end

    -- 保存客户端实例
    RedisManager.client = client
    print('Redis 连接成功')
    return client
end

--- 关闭 Redis 连接
function RedisManager.close()
    -- 关闭 Redis 连接并清空客户端引用
    if RedisManager.client then
        RedisManager.client:close()
        RedisManager.client = nil
        print('Redis 连接已关闭')
    end
end

--- 获取 Redis 客户端
--- @return table|nil Redis 客户端
function RedisManager.getClient()
    -- 返回当前 Redis 客户端实例
    return RedisManager.client
end

-- 字符串操作封装

--- 设置键值
--- @param key string 键
--- @param value string 值
--- @return boolean 是否成功
function RedisManager.set(key, value)
    -- 设置键值对，如果键已存在则覆盖
    local client = RedisManager.getClient()
    if not client then return false end
    return client:set(key, value)
end

--- 获取键值
--- @param key string 键
--- @return string|nil 值
function RedisManager.get(key)
    -- 获取键对应的值，键不存在返回 nil
    local client = RedisManager.getClient()
    if not client then return nil end
    return client:get(key)
end

--- 设置键值并指定过期时间（秒）
--- @param key string 键
--- @param value string 值
--- @param seconds number 过期秒数
--- @return boolean 是否成功
function RedisManager.setex(key, value, seconds)
    -- 设置键值对并指定过期时间（秒）
    -- 超过指定时间后键会自动删除
    local client = RedisManager.getClient()
    if not client then return false end
    return client:setex(key, seconds, value)
end

--- 删除键
--- @param key string 键
--- @return number 删除的键数量
function RedisManager.del(key)
    -- 删除指定的键，返回删除的键数量
    local client = RedisManager.getClient()
    if not client then return 0 end
    return client:del(key)
end

-- 哈希操作封装

--- 设置哈希字段
--- @param key string 哈希键
--- @param field string 字段名
--- @param value string 字段值
--- @return boolean 是否成功
function RedisManager.hset(key, field, value)
    -- 设置哈希表中的字段值，字段不存在则创建，存在则更新
    local client = RedisManager.getClient()
    if not client then return false end
    return client:hset(key, field, value)
end

--- 获取哈希字段
--- @param key string 哈希键
--- @param field string 字段名
--- @return string|nil 字段值
function RedisManager.hget(key, field)
    -- 获取哈希表中指定字段的值，字段不存在返回 nil
    local client = RedisManager.getClient()
    if not client then return nil end
    return client:hget(key, field)
end

--- 获取哈希所有字段
--- @param key string 哈希键
--- @return table 所有字段和值
function RedisManager.hgetall(key)
    -- 获取哈希表中所有字段和值，返回数组格式
    -- 数组中奇数索引为字段名，偶数索引为字段值
    local client = RedisManager.getClient()
    if not client then return {} end
    return client:hgetall(key)
end

--- 删除哈希字段
--- @param key string 哈希键
--- @param field string 字段名
--- @return number 删除的字段数量
function RedisManager.hdel(key, field)
    -- 删除哈希表中的指定字段，返回删除的字段数量
    local client = RedisManager.getClient()
    if not client then return 0 end
    return client:hdel(key, field)
end

-- 列表操作封装

--- 左侧推入列表
--- @param key string 列表键
--- @param value string 值
--- @return number 列表长度
function RedisManager.lpush(key, value)
    -- 将值推入列表左侧（头部），返回列表长度
    local client = RedisManager.getClient()
    if not client then return 0 end
    return client:lpush(key, value)
end

--- 右侧推入列表
--- @param key string 列表键
--- @param value string 值
--- @return number 列表长度
function RedisManager.rpush(key, value)
    -- 将值推入列表右侧（尾部），返回列表长度
    local client = RedisManager.getClient()
    if not client then return 0 end
    return client:rpush(key, value)
end

--- 获取列表范围
--- @param key string 列表键
--- @param start number 起始索引
--- @param stop number 结束索引
--- @return table 列表元素
function RedisManager.lrange(key, start, stop)
    -- 获取列表指定范围内的元素
    -- start 和 stop 使用索引，0 表示第一个元素，-1 表示最后一个元素
    local client = RedisManager.getClient()
    if not client then return {} end
    return client:lrange(key, start, stop)
end

--- 左侧弹出
--- @param key string 列表键
--- @return string|nil 弹出的值
function RedisManager.lpop(key)
    -- 从列表左侧（头部）弹出一个元素并返回
    -- 列表为空时返回 nil
    local client = RedisManager.getClient()
    if not client then return nil end
    return client:lpop(key)
end

--- 右侧弹出
--- @param key string 列表键
--- @return string|nil 弹出的值
function RedisManager.rpop(key)
    -- 从列表右侧（尾部）弹出一个元素并返回
    -- 列表为空时返回 nil
    local client = RedisManager.getClient()
    if not client then return nil end
    return client:rpop(key)
end

-- 集合操作封装

--- 添加集合成员
--- @param key string 集合键
--- @param member string 成员
--- @return number 添加的成员数量
function RedisManager.sadd(key, member)
    -- 向集合中添加成员，成员已存在则忽略
    -- 返回实际添加的成员数量
    local client = RedisManager.getClient()
    if not client then return 0 end
    return client:sadd(key, member)
end

--- 获取所有集合成员
--- @param key string 集合键
--- @return table 所有成员
function RedisManager.smembers(key)
    -- 获取集合中的所有成员
    -- 集合中的成员是无序且唯一的
    local client = RedisManager.getClient()
    if not client then return {} end
    return client:smembers(key)
end

--- 判断成员是否在集合中
--- @param key string 集合键
--- @param member string 成员
--- @return boolean 是否存在
function RedisManager.sismember(key, member)
    -- 判断成员是否存在于集合中
    -- 存在返回 true，不存在返回 false
    local client = RedisManager.getClient()
    if not client then return false end
    return client:sismember(key, member)
end

--- 删除集合成员
--- @param key string 集合键
--- @param member string 成员
--- @return number 删除的成员数量
function RedisManager.srem(key, member)
    -- 从集合中删除指定成员
    -- 返回实际删除的成员数量
    local client = RedisManager.getClient()
    if not client then return 0 end
    return client:srem(key, member)
end

-- 有序集合操作封装

--- 添加有序集合成员
--- @param key string 有序集合键
--- @param score number 分数
--- @param member string 成员
--- @return number 添加的成员数量
function RedisManager.zadd(key, score, member)
    -- 向有序集合中添加成员及其分数
    -- 成员按分数从小到大排序，分数相同按字典序
    -- 返回实际添加的成员数量
    local client = RedisManager.getClient()
    if not client then return 0 end
    return client:zadd(key, score, member)
end

--- 获取有序集合范围
--- @param key string 有序集合键
--- @param start number 起始索引
--- @param stop number 结束索引
--- @return table 成员列表
function RedisManager.zrange(key, start, stop)
    -- 获取有序集合指定分数范围内的成员
    -- 默认按分数从小到大排序
    local client = RedisManager.getClient()
    if not client then return {} end
    return client:zrange(key, start, stop)
end

--- 获取成员分数
--- @param key string 有序集合键
--- @param member string 成员
--- @return number|nil 分数
function RedisManager.zscore(key, member)
    -- 获取有序集合中指定成员的分数
    -- 成员不存在返回 nil
    local client = RedisManager.getClient()
    if not client then return nil end
    return client:zscore(key, member)
end

-- 测试方法

--- 测试字符串操作
function testStringOperations()
    -- 测试 Redis 字符串类型的基本操作
    print('\n=== 测试字符串操作 ===')
    
    -- 测试 set 和 get
    RedisManager.set('test:name', '张三')
    local name = RedisManager.get('test:name')
    print('设置并获取 name:', name)

    -- 测试 setex（带过期时间）
    RedisManager.setex('test:temp', '10秒后过期', 10)
    print('设置临时键 test:temp')

    -- 测试 del
    RedisManager.del('test:name')
    print('删除键 test:name')
end

--- 测试哈希操作
function testHashOperations()
    -- 测试 Redis 哈希类型的基本操作
    -- 哈希适用于存储对象，如用户信息
    print('\n=== 测试哈希操作 ===')
    
    -- 设置多个字段
    RedisManager.hset('test:user:1', 'name', '李四')
    RedisManager.hset('test:user:1', 'age', '25')
    RedisManager.hset('test:user:1', 'city', '北京')

    -- 获取所有字段
    local user = RedisManager.hgetall('test:user:1')
    print('用户信息:', table.concat(user, ' '))

    -- 获取单个字段
    local name = RedisManager.hget('test:user:1', 'name')
    print('获取 name 字段:', name)

    -- 删除字段
    RedisManager.hdel('test:user:1', 'age')
    print('删除 age 字段')

    -- 删除整个哈希
    RedisManager.del('test:user:1')
    print('删除哈希键 test:user:1')
end

--- 测试列表操作
function testListOperations()
    -- 测试 Redis 列表类型的基本操作
    -- 列表是有序的字符串集合，可以从两端操作
    print('\n=== 测试列表操作 ===')
    
    -- 从左侧推入元素
    RedisManager.lpush('test:mylist', 'item1')
    RedisManager.lpush('test:mylist', 'item2')
    -- 从右侧推入元素
    RedisManager.rpush('test:mylist', 'item3')

    -- 获取列表所有元素
    local items = RedisManager.lrange('test:mylist', 0, -1)
    print('列表内容:', table.concat(items, ', '))

    -- 从左侧弹出
    local left_item = RedisManager.lpop('test:mylist')
    print('左侧弹出:', left_item)

    -- 从右侧弹出
    local right_item = RedisManager.rpop('test:mylist')
    print('右侧弹出:', right_item)

    -- 删除列表
    RedisManager.del('test:mylist')
    print('删除列表键 test:mylist')
end

--- 测试集合操作
function testSetOperations()
    -- 测试 Redis 集合类型的基本操作
    -- 集合是无序且唯一的字符串集合
    print('\n=== 测试集合操作 ===')
    
    -- 添加成员
    RedisManager.sadd('test:myset', 'member1')
    RedisManager.sadd('test:myset', 'member2')
    RedisManager.sadd('test:myset', 'member3')

    -- 获取所有成员
    local members = RedisManager.smembers('test:myset')
    print('集合成员:', table.concat(members, ', '))

    -- 判断成员是否存在
    local exists = RedisManager.sismember('test:myset', 'member2')
    print('member2 是否存在:', exists)

    -- 删除成员
    RedisManager.srem('test:myset', 'member1')
    print('删除 member1')

    -- 删除集合
    RedisManager.del('test:myset')
    print('删除集合键 test:myset')
end

--- 测试有序集合操作
function testSortedSetOperations()
    -- 测试 Redis 有序集合类型的基本操作
    -- 有序集合是带分数的集合，按分数排序
    -- 适用于排行榜、评分系统等场景
    print('\n=== 测试有序集合操作 ===')
    
    -- 添加成员及其分数
    RedisManager.zadd('test:leaderboard', 100, 'player1')
    RedisManager.zadd('test:leaderboard', 200, 'player2')
    RedisManager.zadd('test:leaderboard', 150, 'player3')

    -- 获取排行榜（按分数升序）
    local players = RedisManager.zrange('test:leaderboard', 0, -1)
    print('排行榜:', table.concat(players, ', '))

    -- 获取指定成员的分数
    local score = RedisManager.zscore('test:leaderboard', 'player2')
    print('player2 分数:', score)

    -- 删除有序集合
    RedisManager.del('test:leaderboard')
    print('删除有序集合键 test:leaderboard')
end

--- 运行所有测试
function runAllTests()
    -- 运行所有 Redis 操作测试
    -- 依次测试字符串、哈希、列表、集合、有序集合
    print('开始运行 Redis 测试...')

    -- 连接到本地 Redis 服务器
    -- 参数：主机地址、端口、密码、数据库编号
    local connected = RedisManager.connect('127.0.0.1', 6379, nil, 0)
    if not connected then
        print('无法连接到 Redis，请检查服务是否启动')
        return
    end

    -- 依次运行各类数据结构的测试
    testStringOperations()      -- 字符串操作测试
    testHashOperations()        -- 哈希操作测试
    testListOperations()        -- 列表操作测试
    testSetOperations()         -- 集合操作测试
    testSortedSetOperations()  -- 有序集合操作测试

    -- 关闭 Redis 连接
    RedisManager.close()
    print('\n所有测试完成')
end

-- 主入口
-- 当直接运行此文件时，自动执行所有测试
-- 当作为模块被 require 时，只返回 RedisManager
if arg and arg[0] and arg[0]:match('redisDemo%.lua$') then
    runAllTests()
end

-- 返回 RedisManager 模块，供其他文件引用
return RedisManager